### ISSUE TITLE
I get an error: SLF4J: No SLF4J providers were found 

### ISSUE THREAD

**Issue by mswertz** [larsgrefer/dart-sass-java#184]
I got error:

SLF4J: No SLF4J providers were found 

I tested in v2.0.0.
Seems to be fixed in 1.10.0

Thanks for maintaining this!
Best wishes from molgenis project, http://github.com/molgenis/molgenis-emx2

**Comment by larsgrefer** [comment]
Which version of slf4j and which slf4j provider (version) are you using in your project?

1.10.0 uses Java 8 and Slf4j 1.7.36
2.0.0 uses Java 17 and Slf4j 2.0.4
