### ISSUE TITLE
Only Java > Version 17 supported?

### ISSUE THREAD

**Issue by rider87** [larsgrefer/dart-sass-java#231]
Hi,

I´m trying:

```
public class Test {

public static void main(String[] args) throws IOException, SassCompilationFailedException {

	try (SassCompiler sassCompiler = SassCompilerFactory.bundled()) {
		CompileSuccess compileSuccess = sassCompiler.compileFile(new File("src/main/resources/foo/bar.scss"));

		// get compiled css
		String css = compileSuccess.getCss();
	}
}
}
```

Is this lib only available with Java 17 ?

I´m using Version 2.2.1

**Comment by rider87** [comment]
Ok, seems 1.12.0 is working... But I got: ClassNotFoundException: com.google.protobuf.GeneratedMessageV3
Which dependency do I missed?

**Comment by larsgrefer** [comment]
Version 1.x is Java 8+ and Version 2.x is Java 17+

The dependency information is published as Maven Pom and Gradle Module Metatdata

For the current 1.x version these dependencies are needed:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- project :sass-embedded-protocol
|    \--- com.google.protobuf:protobuf-java:3.22.1
\--- org.slf4j:slf4j-api:1.7.36
```

**Comment by rider87** [comment]
Thank you, it works now.
