### ISSUE TITLE
Compile from App Server Class Path / Can't find stylesheet to import.

### ISSUE THREAD

**Issue by rider87** [larsgrefer/dart-sass-java#232]
Hi,

I´m currently would like to integrate this Library into my Webapp (WildFly) application.

My process is like this:
- Open the file
- Load content to string
- Change color codes to my needs (search and replace) and get a new string
- Compile this new adjusted string (with other colors codes)

It seems this lib is not handling vFS from the war, because I got an issue that I cannot open the path:
`Error: java.lang.IllegalArgumentException: Can't handle url: vfs:/Applications/Software/wildfly-21.0.0.Final/standalone/deployments/myApp.war/WEB-INF/lib/myExternalJarApp-1.0-SNAPSHOT.jar/files/template/jsf/primefaces/rain/sass/theme/_theme_dark`

If I execute the same code via simple Main method (no WildFly), it will work.

My SCSS - File is something linke this:
`$primaryLightColor: #eeee90 !default;
$primaryColor: #eeee89 !default;
$primaryDarkColor: #eeee88 !default;
$primaryDarkerColor: #eeee87 !default;
$primaryTextColor: #eeee86 !default;

@import '../sass/theme/_theme_light';`

I´ve tried this and than I got this exception
`URL url = Thread.currentThread().getContextClassLoader()
					.getResource("files/template/layout-light.scss");
CompileSuccess compileSuccess = sassCompiler.compile(url);`

Issue seems for me in the class CustomUrlImporter" in function: 
**protected boolean isFile(URL url)** 

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/9787533/226105606-1388b224-693d-4ea2-b217-555b586ba93b.png">

If I execute it via Main function I have as protocol:
![image](https://user-images.githubusercontent.com/9787533/226105629-0be961d0-8cb3-4c61-9c23-83c2175bd4ab.png)

If I execute via App - Server I have another protocol:
![image](https://user-images.githubusercontent.com/9787533/226105645-13caae52-19f3-47f7-a549-d96d4bf96ea3.png)

No condition is matching and therefore I got this exception:
![image](https://user-images.githubusercontent.com/9787533/226105906-95c6c271-70db-475f-8b73-a3f09e4d75eb.png)

---------------------------------------------
At the end I would also need only the string from the File, do some color changes, compile it and get the css code....
Than I´m trying it with the other function (compileScssString):

Here the code for it:
`URL url = Thread.currentThread().getContextClassLoader()
					.getResource("files/template/layout-light.scss");
File file = new File(url.getFile());
String content = IOUtils.toString(new FileInputStream(file), StandardCharsets.UTF_8);
CompileSuccess compileSuccess = sassCompiler.compileScssString(content);`

But than I´m got this exception (also in my simple Main - function):
```
Exception in thread "main" de.larsgrefer.sass.embedded.SassCompilationFailedException: Error: Can't find stylesheet to import.
  ╷
4 │ @import '../../sass/variables/_layout_light';
```

String content is like this:
```
$primaryColor: #eeee89;
$primaryTextColor: #eeee86;

@import '../../sass/variables/_layout_light';
@import '../../sass/layout/_layout';
```
So seems sassCompiler.compileScssString(content); cannot handle references to other files?
And this is working?
CompileSuccess compileSuccess = sassCompiler.compileFile(file);

Are there some fixes needed in the lib or I´m doing something wrong?

**Comment by larsgrefer** [comment]
Could you share an example project which I can try/debug myself?

> It seems this lib is not handling vFS from the war, because I got an issue that I cannot open the path:

Yes, the vfs protocol seems to be the problem here. When resolving imports like `../foo`, the import could refer to `../foo.scss`, `../foo.sass`, `../_foo.scss`, `../_foo.sass`. The `AutoCanonicalizingImporter` generates all the possible targets and then checks, which of these actually exist (is an actual file). This check is only implemented for `file:`, `jar:` and `http(s):` protocols, but fails for `vfs:` URLs.

> So seems sassCompiler.compileScssString(content); cannot handle references to other files?

Yes, compileScssString cannot handle (relative) imports by default, because the compiler can't know where to search.
You could try to circumvent this, by providing an additional Importer to `SassCompiler#registerImporter`.

**Comment by rider87** [comment]
Thank you for your answer....

As example you can use any WildFly project and than just add this line:

`URL url = Thread.currentThread().getContextClassLoader() .getResource("files/template/layout-light.scss"); CompileSuccess compileSuccess = sassCompiler.compile(url);`

Is there any option to extend the protocols that it works also for `vfs`?
Otherwise I will get always this exception.

> Yes, compileScssString cannot handle (relative) imports by default, because the compiler can't know where to search. You could try to circumvent this, by providing an additional Importer to `SassCompiler#registerImporter`.

Not sure how I can do this here....

**Comment by larsgrefer** [comment]
Could you try again with version [1.13.0](https://github.com/larsgrefer/dart-sass-java/releases/tag/1.13.0) ?

**Comment by rider87** [comment]
Thank you Lars, that´s working.
I´ve created a new ticket regarding the issue:
`CompileSuccess compileSuccess = sassCompiler.compileScssString(content) `

https://github.com/larsgrefer/dart-sass-java/issues/236
