### ISSUE TITLE
sassCompiler.compileScssString(content) -> Error: Can't find stylesheet to import.

### ISSUE THREAD

**Issue by rider87** [larsgrefer/dart-sass-java#236]
Hi Lars, 

I have currently this process, which will be used for my user to change the color codes dynamically. 

1. Load scss file from resource folder (InputStream)
2. Load from InputStream the connent in a String value
3. Load a property file which have some mappings
4. change value from the mapping (colors) with the object from the database, which contains the new color codes from user. Search and replace String from (2)
**5. load the adjusted String and compile this String with:** 

```
String content = // adjusted String
CompileSuccess compileSuccess = sassCompiler.compileScssString(content);
```

Scss file looks like:
```
$primaryLightColor: #eeee90 !default;
$primaryColor: #eeee89 !default;
$primaryDarkColor: #eeee88 !default;
$primaryDarkerColor: #eeee87 !default;
$primaryTextColor: #eeee86 !default;

@import '../sass/theme/_theme_light';
```

This issue is now the @import '../sass/theme/_theme_light';
Seems like it cannot handle such path.

If I do the same with:
`CompileSuccess compileSuccess = sassCompiler.compileFile(file);` it works.

How cant this be fixed?
A temp solution would be do create a temp file with the new content, but is there also another option with sassCompiler.compileScssString(content); ?

**Comment by larsgrefer** [comment]
When you pass a String into `compileScssString()`, the compiler has no context for resolving the import.
How should the compiler know where `../sass` is, when it is just given the String?

You can help the compiler by passing additional importers into `SassCompiler.registerImporter()`.
In your case, something like this might help:

```java
sassCompiler.registerImporter(new ClasspathImporter().autoCanonicalize());
sassCompiler.registerImporter(new RelativeUrlImporter(resourceUrl).autoCanonicalize());
```

The classpath importer can resolve everything on the classpath. Note that the imports must be relative to the classpath root for this to work. Given your example from #232 your import should then look something like this:
```
@import "files/template/jsf/primefaces/rain/sass/theme/_theme_light";
```

The RelativeUrlImporter will try to resolve imports relative to the given base url.

**Comment by rider87** [comment]
awesome - this is working.
Thank you so much, Lars.
