### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by appt2** [larsgrefer/dart-sass-java#461]
hello @larsgrefer can you adding android port?

**Comment by larsgrefer** [comment]
With version 3.4.2 we now have an Android variant: https://repo1.maven.org/maven2/de/larsgrefer/sass/sass-embedded-android/3.4.2/

There is also an example app which uses the new library: https://github.com/larsgrefer/dart-sass-java/blob/3.x/test-projects/android-app/src/main/java/de/larsgrefer/sass/embedded/android/test/MainActivity.java

**Comment by appt2** [comment]
> With version 3.4.2 we now have an Android variant: https://repo1.maven.org/maven2/de/larsgrefer/sass/sass-embedded-android/3.4.2/
> 
> There is also an example app which uses the new library: https://github.com/larsgrefer/dart-sass-java/blob/3.x/test-projects/android-app/src/main/java/de/larsgrefer/sass/embedded/android/test/MainActivity.java

Thank you, can the previous methods be used?

**Comment by appt2** [comment]
now testing and result

02-19 11:30:19.377   985   985 E lib     : No dart binary found for ABIs [arm64-v8a, armeabi-v7a, armeabi]
02-19 11:30:19.377   985   985 E lib     : java.lang.IllegalStateException: No dart binary found for ABIs [arm64-v8a, armeabi-v7a, armeabi]
02-19 11:30:19.377   985   985 E lib     : 	at de.larsgrefer.sass.embedded.android.AndroidConnectionFactory.bundled(AndroidConnectionFactory.java:30)
02-19 11:30:19.377   985   985 E lib     : 	at de.larsgrefer.sass.embedded.android.AndroidSassCompilerFactory.bundled(AndroidSassCompilerFactory.java:17)
02-19 11:30:19.377   985   985 E lib     : 	at com.example.apksinger.MainActivity.onCreate(MainActivity.java:51)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.Activity.performCreate(Activity.java:8891)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.Activity.performCreate(Activity.java:8856)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1471)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
02-19 11:30:19.377   985   985 E lib     : 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-19 11:30:19.377   985   985 E lib     : 	at android.os.Looper.loopOnce(Looper.java:224)
02-19 11:30:19.377   985   985 E lib     : 	at android.os.Looper.loop(Looper.java:318)
02-19 11:30:19.377   985   985 E lib     : 	at android.app.ActivityThread.main(ActivityThread.java:8762)
02-19 11:30:19.377   985   985 E lib     : 	at java.lang.reflect.Method.invoke(Native Method)
02-19 11:30:19.377   985   985 E lib     : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
02-19 11:30:19.377   985   985 E lib     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by larsgrefer** [comment]
Have you used this setting in your apps build.gradle?

https://github.com/larsgrefer/dart-sass-java/blob/64fc9f7c4b3e91d311467bcf9aec41c00d464dec/test-projects/android-app/build.gradle#L18

**Comment by appt2** [comment]
> Have you used this setting in your apps build.gradle?
> 
> https://github.com/larsgrefer/dart-sass-java/blob/64fc9f7c4b3e91d311467bcf9aec41c00d464dec/test-projects/android-app/build.gradle#L18

yes adding and not work compile to system android can you make apk demo file?

**Comment by larsgrefer** [comment]
Just clone this repo and run `./gradlew test-projects:android-app:installDebug`

**Comment by appt2** [comment]
hi @larsgrefer  im winter code to compile scss

```java

package Ninja.coder.Ghostemane.code.tasks.app;

import Ninja.coder.Ghostemane.code.ColorAndroid12;
import android.content.Context;
import android.widget.EditText;
import android.widget.LinearLayout;
import com.google.android.material.bottomsheet.BottomSheetDialog;
import com.google.android.material.color.MaterialColors;
import com.sass_lang.embedded_protocol.InboundMessage;
import de.larsgrefer.sass.embedded.CompileSuccess;
import de.larsgrefer.sass.embedded.SassCompiler;
import de.larsgrefer.sass.embedded.connection.CompilerConnection;
import de.larsgrefer.sass.embedded.connection.Packet;
import java.io.File;
import java.io.IOException;

public class SassForAndroid {
  protected static SassCompiler compiler;

  static {
    compiler =
        new SassCompiler(
            new CompilerConnection() {

              @Override
              public void sendMessage(Packet<InboundMessage> arg0) {}

              @Override
              public void sendMessage(int arg0, InboundMessage arg1) {}

              @Override
              public Packet<com.sass_lang.embedded_protocol.OutboundMessage> readResponse() {
                return null;
              }

              @Override
              public void close() {}
            });
  }

  public static String CompileForStringScss(String input) {
    try {
      CompileSuccess sb = compiler.compileScssString(input);
      return sb.getCss();
    } catch (Exception err) {
      return err.getLocalizedMessage();
    }
  }

  public static void CompilerForFile(File input, String output) {
    try {
      CompileSuccess sb = compiler.compileFile(input);
      output = sb.getCss();
    } catch (Exception err) {
      err.printStackTrace();
    }
  }

  public static void CompileForStringSass(String input, String output) {
    try {
      CompileSuccess sb = compiler.compileSassString(input);
      output = sb.getCss();
    } catch (Exception err) {
      err.printStackTrace();
    }
  }

  public static void run(Context context, String input) {
    var sheet = new BottomSheetDialog(context);
    EditText tv = new EditText(context);
    LinearLayout.LayoutParams param =
        new LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT);
    tv.setLayoutParams(param);
    param.rightMargin = 3;
    param.leftMargin = 3;
    tv.setTextColor(MaterialColors.getColor(tv, ColorAndroid12.colorOnSurface, 0));
    tv.setPadding(9, 9, 9, 9);
    sheet.setContentView(tv);
    tv.setText(CompileForStringScss(input));
    sheet.show();
  }
}
```


result 

```java
 Attempt to invoke virtual method 'int de.larsgrefer.sass.embedded.connection.Packet.getCompilationId()' on a null object reference
```
plz help me to fix

**Comment by appt2** [comment]
and convert api 26 to 21

**Comment by larsgrefer** [comment]
When you replace the `CompilerConnection` with a dummy implementation, its no wonder nothing works.
The `NullPointerException` happens, because your `readResponse()` method returns null.

This should be everything you need: https://github.com/larsgrefer/dart-sass-java/blob/5361ff6f3da10ea729040627267b41cca5d49bcd/test-projects/android-app/src/main/java/de/larsgrefer/sass/embedded/android/demo/MainActivity.java#L31-L36

**Comment by appt2** [comment]
@larsgrefer tnks fixed view in <a href = "https://github.com/appt2/Ghost-web-ide/actions/runs/8108167355">view code<a/>

bro can you convert api 26 to 21?

**Comment by appt2** [comment]
Task :app:processReleaseMainManifest FAILED
/storage/emulated/0/AndroidIDEProjects/Ghost-web-ide/app/src/main/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 21 cannot be smaller than version 26 declared in library [de.larsgrefer.sass:sass-embedded-android:3.5.1] /data/data/com.itsaky.androidide/files/home/.gradle/caches/transforms-3/175657cbb8d3839214e0a1b6ab289f29/transformed/jetified-sass-embedded-android-3.5.1/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 26,
		or use tools:overrideLibrary="de.larsgrefer.sass.embedded.android" to force usage (may lead to runtime failures)

See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.


@larsgrefer  plz fix

**Comment by larsgrefer** [comment]
@appt2 You have to update to 3.6.0.

You are still using 3.5.1 which still has a minSdk of 26

**Comment by appt2** [comment]
> @appt2 You have to update to 3.6.0.
> 
> You are still using 3.5.1 which still has a minSdk of 26

last version mevan 3.5.1
https://mvnrepository.com/artifact/de.larsgrefer.sass/sass-embedded-android/3.5.1

**Comment by larsgrefer** [comment]
No: https://repo1.maven.org/maven2/de/larsgrefer/sass/sass-embedded-android/3.6.0/

**Comment by appt2** [comment]
> No: https://repo1.maven.org/maven2/de/larsgrefer/sass/sass-embedded-android/3.6.0/

oh tnks

**Comment by appt2** [comment]
Well, the Android version has been ported, so I will close this issue
