### ISSUE TITLE
sass Code Formater

### ISSUE THREAD

**Issue by appt2** [larsgrefer/dart-sass-java#474]
hello @larsgrefer  can you adding keyword List<>

and code formatet sass?

**Comment by larsgrefer** [comment]
What do you mean?

**Comment by appt2** [comment]
> What do you mean?

Well, now your library is a sass code executor, this is true, well, this code executor works like jdk, so it needs to support a sorter and keywords, I mean the same beautiful print that is in all ide and for  A better display of the code is used

**Comment by appt2** [comment]
```java
  private String formatJson(String code) {
    Gson gson = new GsonBuilder().setPrettyPrinting().create();
    JsonParser jp = new JsonParser();
    JsonElement je = jp.parse(code);
    return gson.toJson(je);
  }

```

For example, this is a code sorter for Json with the help of the Gson library

**Comment by larsgrefer** [comment]
This library only maps the features of the sass-embedded-protocol into java.

Code formatting and syntax higlighting is not part of the protocol.

See https://github.com/sass/sass/blob/main/spec/embedded-protocol.md

**Comment by appt2** [comment]
@larsgrefer  tnks to adding api 21

**Comment by larsgrefer** [comment]
Sass Formatting is currently not part of the protocol spec.

If it gets implemented in the protocol and dart-sass, I can implement it here
